### PR TITLE
Cleanup ZuulReporter

### PR DESCRIPTION
**Pull request by vweevers**

### CODE REVIEW

**Comment by vweevers** [comment]
Closes #101.

**Comment by vweevers** [comment]
Failing job on node 8: https://travis-ci.org/airtap/airtap/jobs/354791423

**Comment by vweevers** [comment]
Android 6.0 failed:

```
airtap browser error (android@6.0: [get("http://airtap.local:38465/__zuul")] 
Error response status: 13, UnknownError - An unknown server-side error occurred while 
processing the command. Selenium error: An unknown server-side error occurred while 
processing the command. Original error: Could not proxy. Proxy error: UiAUtomator shut 
down unexpectedly), restarting
```

But it was properly retried by airtap, and then succeeded (as far as I can see). The end of the build output shows a plan mismatch:

```
not ok 79 plan != count
  ---
    operator: fail
    expected: 50
    actual:   51
```

Perhaps the first failed attempt did result in an assertion?

**Comment by vweevers** [comment]
It would help to debug situations like these if we:

1. Replace `console.log` calls with `debug`. Standard output should be reserved for TAP.
2. Add messages to assertions. E.g. `t.is(results.passed, 3, '3 tests passed')`.

Opening issues.

**Comment by vweevers** [comment]
On the one hand, I want to look into this failure now, because it's random (of the two node 8 builds, only one failed). On the other, I don't want it to block progress. Atm I can't make sense of the failure. So I'm restarting the job.

**Comment by vweevers** [comment]
It's green now. @ralphtheninja @yeskunall Do you agree that the failure is most likely unrelated? And that we can merge this?

**Comment by ralphtheninja** [comment]
> On the one hand, I want to look into this failure now, because it's random (of the two node 8 builds, only one failed). On the other, I don't want it to block progress. Atm I can't make sense of the failure. So I'm restarting the job.

We should also add more `debug` statements. It will help finding problems like this.

**Comment by ralphtheninja** [comment]
> airtap browser error (android@6.0: [get("http://airtap.local:38465/__zuul")] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: UiAUtomator shut down unexpectedly), restarting

I wonder if we can get more information from sauce labs as to why something didn't work. More descriptive errors I mean.

**Comment by vweevers** [comment]
> I wonder if we can get more information from sauce labs as to why something didn't work. More descriptive errors I mean.

👍 Opening an issue.

**Pull request merged**
