### PR TITLE
Add standard

### LINKED ISSUE #11: Add standard

### PR DESCRIPTION
**Pull request by feross**
Fixes #11.

Run `standard --fix` across the codebase, excluding the files modified in the PR https://github.com/airtap/airtap/pull/41 to avoid creating a merge conflict. (We can run `standard --fix` once more after that PR is merged.)

Also, excluded files related to Jasmine, Mocha, QUnit, Phantom, etc. from being tested with `standard` (though I think these were affected by `--fix`). These files will eventually be removed so there's no reason to put effort into making these files standard.

Lastly, added `standard` to the `npm test` command, but in a way that doesn't fail the tests, since there are still a few hundred fixes that need to be made.

```
npm run lint | wc -l                                                                                  standard ✱
standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
     434
```

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@feross Good call. I was about to push for getting `standard` in as soon as possible before refactoring etc.

**Comment by vweevers** [comment]
LGTM. Build is failing though, same error on all jobs:

```
Uncaught AssertionError [ERR_ASSERTION]: false == true
      at /home/travis/build/airtap/airtap/test/unit/browserify-builder.js:25:12
      at /home/travis/build/airtap/airtap/lib/builder-browserify.js:69:7
      at /home/travis/build/airtap/airtap/node_modules/browserify/index.js:776:13
```

**Comment by feross** [comment]
@vweevers I'm working on it.

**Comment by feross** [comment]
Tests are passing! ✨

**Comment by vweevers** [comment]
Out of curiosity, what did you change?

**Comment by ralphtheninja** [comment]
I resolved the conflict in `package.json` will merge once tests pass.

**Comment by feross** [comment]
@vweevers Modifying the fixture files (e.g. to remove semis) caused some of the tests that relied on exact output to fail.

I reverted the changes to the fixture files and ignored that whole folder. I think we can work on removing stuff from the `ignore` field in `package.json` slowly over time:

https://github.com/airtap/airtap/blob/29956a212c3ab66162ce81dba6622e4406af1c8b/package.json#L78-L86

**Comment by ralphtheninja** [comment]
0.0.2

**Pull request merged**
