### PR TITLE
remove moar zuul (prefix etc)

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@vweevers Maybe release 0.0.5 after this?

**Comment by vweevers** [comment]
I wonder why zuul used the underscore prefix.

**Comment by feross** [comment]
I believe they used the `__` prefix to reduce the likelihood of colliding with a user-specified route. Don't requests that don't match the route `/__zuul` get passed through to the user's server, if they specify one?

**Comment by feross** [comment]
Re-triggered the failing Node 8 build and it passes now, merging!

**Pull request merged**
