### PR TITLE
fix: zuul.run(cb) calls back with (err, passed)

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/airtap/airtap/issues/46

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@airtap/all Maybe release `0.0.2` after this?

**Comment by ralphtheninja** [comment]
Merging this since I need it for https://github.com/airtap/airtap/issues/9

**Comment by vweevers** [comment]
(lgtm)

**Comment by ralphtheninja** [comment]
0.0.2

**Pull request merged**
